OS_RELEASE_FIELDS:append = " IMAGE_VERSION KERNEL_VERSION UBOOT_VERSION"
IMAGE_RELEASE_VERSION ?= "eamb9918-sdcard_0.0.0"
IMAGE_VERSION = "${IMAGE_RELEASE_VERSION}"
KERNEL_RELEASE_VERSION ?= "Linux version 5.15.32"
KERNEL_VERSION = "${KERNEL_RELEASE_VERSION}"
UBOOT_RELEASE_VERSION ?= "U-Boot 2022.04"
UBOOT_VERSION = "${UBOOT_RELEASE_VERSION}"

