OS_RELEASE_FIELDS_append = " IMAGE_VERSION KERNEL_VERSION UBOOT_VERSION"
IMAGE_RELEASE_VERSION ?= "eamb9918-sdcard_1.1.0"
IMAGE_VERSION = "${IMAGE_RELEASE_VERSION}"

KERNEL_RELEASE_VERSION ?= "Linux version 5.4.70"
KERNEL_VERSION = "${KERNEL_RELEASE_VERSION}"

UBOOT_RELEASE_VERSION ?= "U-Boot 2020.04"
UBOOT_VERSION = "${UBOOT_RELEASE_VERSION}"
