OS_RELEASE_FIELDS:append = " IMAGE_VERSION KERNEL_VERSION UBOOT_VERSION"
IMAGE_RELEASE_VERSION ?= "eamb9918-sdcard_2.0.0"
IMAGE_VERSION = "${IMAGE_RELEASE_VERSION}"
KERNEL_RELEASE_VERSION ?= "Linux version 5.10.72"
KERNEL_VERSION = "${KERNEL_RELEASE_VERSION}"
UBOOT_RELEASE_VERSION ?= "U-Boot 2021.04"
UBOOT_VERSION = "${UBOOT_RELEASE_VERSION}"

